In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# [Problem 1] Matrix product is calculated manually

*Question:*
$$A=\begin{bmatrix}-1&2&3\\
4&-1&6\\
7&8&-9
\end{bmatrix},B=\begin{bmatrix}0&2&1\\
0&2&-8\\
2&9&-1
\end{bmatrix}$$

*Answer:*
$$
\begin{bmatrix}(-1*0)+(2*0)+(3*2)&(-1*2)+(2*2)+(3*9)&(-1*1)+(2*8)+(3*-1)\\
(4*0)+(-5*0)+(6*2)&(4*2)+(-5*2)+(6*9)&(4*1)+(-5*-8)+(6*-1)\\
(7*0)+(8*0)+(-9*2)&(7*1)+(8*-8)+(-9*-1)
\end{bmatrix}
$$

**Final Answer:**
$$
\begin{bmatrix}
6&29&-20\\
12&52&38\\
-18&12&-48
\end{bmatrix}
$$



# [Problem 2] Calculation by NumPy function

In [51]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
answer_1 = np.matmul(a_ndarray,b_ndarray)
print(answer_1)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# [Problem 3] Implementation of calculation of a certain element

In [14]:
answer_2 = (a_ndarray[0][0]*b_ndarray[0][0])+(a_ndarray[0][1]*b_ndarray[0][1])+(a_ndarray[0][2]*b_ndarray[2][0])
print(answer_2)

10


# [Problem 4] Creating a function that performs matrix multiplication

In [53]:
def calculate_matrix(a,b):
    answer_2_1 = np.empty([3,3])
    for row_1 in range(a.shape[0]):
        for column_1 in range(b.shape[1]):
            answer_2_1[row_1][column_1] = sum(a[row_1,:]*b[:,column_1])
    return answer_2_1      
print(calculate_matrix(a_ndarray,b_ndarray))    

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# [Problem 5] Judge the input whose calculation is not defined

In [19]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
if (d_ndarray.shape[0]==e_ndarray.shape[1]):
     print(calculate_matrix(a_ndarray,b_ndarray))    
else:
     print("This matrix can not be calculated")

This matrix can not be calculated


# [Problem 6] Transposition

In [50]:
def calculate_matrix_2(a,b):
    
    if(a.shape[0]==b.shape[1]):
        results = np.matmul(a,b)
        return results
    else:    
        return "This matrix can not be calculated"
print(calculate_matrix_2(d_ndarray,e_ndarray))  

This matrix can not be calculated


In [55]:
transposed_ndarray = np.transpose(e_ndarray)
print("after transpose {}, {}".format(d_ndarray.shape,transposed_ndarray.shape))
print("----------------------")
print("solution {}".format(calculate_matrix_2(d_ndarray,transposed_ndarray)))

after transpose (2, 3), (3, 2)
----------------------
solution [[ 46  -4]
 [-34  73]]
